apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  namespace: influxdb
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: local
  hostPath:
    path: /home/master1/influxdata/data
